#!/usr/bin/env python3
"""
Axisymmetric FEA of piston crown using CalculiX (ccx).
Generates .inp file, runs ccx, extracts results.
"""
import numpy as np
import subprocess
import os
import sys

# Dimensions (mm)
bore_radius = 94.5 / 2  # mm
crown_thickness = 12.294  # mm

# Material (forged steel)
young_modulus = 210000.0  # MPa
poisson = 0.29
density = 7.85e-9  # tonne/mm³ (for mass, not needed for static)

# Load
pressure = 30.0  # MPa (300 bar)

# Mesh density
nr = 10  # elements radial
nz = 5   # elements thickness

# Node numbering: grid of (nr+1) × (nz+1)
nnodes = (nr + 1) * (nz + 1)
nelements = nr * nz

print(f"Generating axisymmetric mesh: {nnodes} nodes, {nelements} elements")
print(f"Radius: 0–{bore_radius} mm, thickness: {crown_thickness} mm")
print(f"Pressure: {pressure} MPa")

# Create nodes
nodes = []
for iz in range(nz + 1):
    z = iz * crown_thickness / nz
    for ir in range(nr + 1):
        r = ir * bore_radius / nr
        nodes.append((r, z))

# Create elements (CAX4: 4‑node axisymmetric quadrilateral)
# Connectivity: (n1, n2, n3, n4) where n1=lower left, n2=lower right,
# n3=upper right, n4=upper left (counter‑clockwise)
elements = []
for iz in range(nz):
    for ir in range(nr):
        n1 = iz * (nr + 1) + ir
        n2 = iz * (nr + 1) + ir + 1
        n3 = (iz + 1) * (nr + 1) + ir + 1
        n4 = (iz + 1) * (nr + 1) + ir
        elements.append((n1 + 1, n2 + 1, n3 + 1, n4 + 1))  # 1‑based indexing

# Write CalculiX input file (.inp)
inp_filename = "piston_crown_axisymmetric.inp"
with open(inp_filename, "w") as f:
    # Header
    f.write("*HEADING\n")
    f.write("Axisymmetric FEA of piston crown (30 MPa pressure)\n")
    f.write("** Generated by Slothworks V12 FEA pipeline\n")
    f.write("*NODE\n")
    # Nodes
    for i, (r, z) in enumerate(nodes):
        f.write(f"{i+1}, {r:.6f}, {z:.6f}, 0.0\n")
    # Elements
    f.write("*ELEMENT, TYPE=CAX4, ELSET=CROWN\n")
    for i, (n1, n2, n3, n4) in enumerate(elements):
        f.write(f"{i+1}, {n1}, {n2}, {n3}, {n4}\n")
    # Material
    f.write("*MATERIAL, NAME=STEEL\n")
    f.write("*ELASTIC\n")
    f.write(f"{young_modulus}, {poisson}\n")
    # Section
    f.write("*SOLID SECTION, ELSET=CROWN, MATERIAL=STEEL\n")
    f.write("1.0,\n")
    # Boundary conditions
    # Fix bottom edge (z=0) in Z direction
    f.write("*NSET, NSET=FIXED_Z\n")
    for iz in [0]:  # only bottom row
        for ir in range(nr + 1):
            node_id = iz * (nr + 1) + ir + 1
            f.write(f"{node_id},\n")
    f.write("*BOUNDARY\n")
    f.write("FIXED_Z, 2, 2\n")  # fix DOF 2 (Z displacement)
    # Symmetry on axis (r=0) in radial direction
    f.write("*NSET, NSET=SYMMETRY_R\n")
    for iz in range(nz + 1):
        for ir in [0]:
            node_id = iz * (nr + 1) + ir + 1
            f.write(f"{node_id},\n")
    f.write("*BOUNDARY\n")
    f.write("SYMMETRY_R, 1, 1\n")  # fix DOF 1 (radial displacement)
    # Pressure load on top surface (z = crown_thickness)
    # Create surface element faces (edges of top elements)
    f.write("*SURFACE, NAME=TOP, TYPE=ELEMENT\n")
    for iz in [nz - 1]:  # top layer of elements
        for ir in range(nr):
            elem_id = iz * nr + ir + 1
            # Face numbering for CAX4: face 3 is top edge (nodes 3‑4)
            f.write(f"{elem_id}, S3\n")
    # Step definition
    f.write("*STEP\n")
    f.write("*STATIC\n")
    f.write("*DLOAD\n")
    f.write("TOP, P, {}\n".format(pressure))
    # Output requests
    f.write("*NODE FILE\n")
    f.write("U\n")
    f.write("*EL FILE\n")
    f.write("S, E\n")
    f.write("*END STEP\n")

print(f"Written {inp_filename}")

# Run CalculiX
print("Running CalculiX ccx...")
try:
    result = subprocess.run(
        ["ccx", "-i", inp_filename.rstrip('.inp')],
        capture_output=True,
        text=True,
        cwd=os.getcwd()
    )
    if result.returncode == 0:
        print("✅ CalculiX completed successfully.")
        # Check for output files
        for ext in ['.dat', '.frd', '.sta']:
            if os.path.exists(inp_filename.rstrip('.inp') + ext):
                print(f"   Output file: {inp_filename.rstrip('.inp') + ext}")
    else:
        print("❌ CalculiX failed:")
        print(result.stderr)
except FileNotFoundError:
    print("❌ CalculiX (ccx) not found in PATH.")
    sys.exit(1)

# Parse .dat file for summary
dat_file = inp_filename.rstrip('.inp') + '.dat'
if os.path.exists(dat_file):
    with open(dat_file, 'r') as df:
        lines = df.readlines()
        # Look for maximum displacements and stresses
        disp_found = False
        stress_found = False
        for line in lines:
            if 'displacements' in line.lower():
                disp_found = True
            if 'stresses' in line.lower():
                stress_found = True
        print(f"   Displacements output: {disp_found}")
        print(f"   Stresses output: {stress_found}")

print("\n🎯 Next steps:")
print("   • Visualize results with CGX: cgx -b piston_crown_axisymmetric.frd")
print("   • Refine mesh for higher accuracy.")
print("   • Add thermal loads (heat flux + convection).")
print("   • Run full 3D piston FEA.")